description: 'Beautiful mac todo app with a built in timer to keep you on track'
name: 'task_timer'
publish_to: 'none'
version: '1.0.0+1'
dependencies:
  cupertino_icons: '^0.1.3'
  intl: '^0.16.1'

  flutter:
    sdk: flutter
dev_dependencies:
  import_sorter: '^1.0.3'
  local_google_fonts: '^1.0.8'
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.7.0 <3.0.0'
flutter:
  fonts:
    - family: 'Tomorrow'
      fonts:
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-100i.ttf'
          style: 'italic'
          weight: 100
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-200i.ttf'
          style: 'italic'
          weight: 200
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-300i.ttf'
          style: 'italic'
          weight: 300
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-400i.ttf'
          style: 'italic'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-500i.ttf'
          style: 'italic'
          weight: 500
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-600i.ttf'
          style: 'italic'
          weight: 600
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-700i.ttf'
          style: 'italic'
          weight: 700
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-800i.ttf'
          style: 'italic'
          weight: 800
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-900i.ttf'
          style: 'italic'
          weight: 900
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-100.ttf'
          weight: 100
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-200.ttf'
          weight: 200
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-300.ttf'
          weight: 300
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-400.ttf'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-500.ttf'
          weight: 500
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-600.ttf'
          weight: 600
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-700.ttf'
          weight: 700
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-800.ttf'
          weight: 800
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-900.ttf'
          weight: 900
  uses-material-design: true
google_fonts:
  fonts:
    - 'Tomorrow'
